### ISSUE TITLE
Autoscrolling stops

### ISSUE THREAD

**Issue by codeskraps** [quarnster/ADBView#23]
I've notice that sometimes the auto scrolling stops working if there's a lot of logs and I have to keep scrolling down to the bottom. This will reactivate the auto scrolling again but it will stop again... and so on, and so on...

I'm guessing is hard to guest when to stop auto scrolling or not if the user is looking at the logs and  wants to stop scrolling.

Perhaps a way to bypass that is the if the cursor is at the very bottom of the log, it will always continue scrolling. Like this you only need to click "Page Down" until the cursor is at the bottom to make sure the log will never stop scrolling and when you want it to stop you can just click "Page Up".

**Comment by quarnster** [comment]
I've forgotten exactly where and how I implemented this ;)

I think it does something like if the last line is visible, do auto scroll otherwise not, but like you said, sometimes a lot of lines get inserted and it's possible that auto scroll is disabled just because it didn't keep up.
