### ISSUE TITLE
Issue with launching adb view.

### ISSUE THREAD

**Issue by ajmeraaxesh** [quarnster/ADBView#24]
Even though I have adb in my path. I  validated by running "which adb" in my ubuntu 12.04.

Where does the "adb" executable need to reside.

Installed Packages/ADBView.sublime-package", line 415, in run
  File "./subprocess.py", line 824, in __init__
  File "./subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'adb

**Comment by Windscar** [comment]
Not sure if you've figured this out yet. 

"which adb" will give you your path to adb. 

In the user settings for ADBVieww, under "command", point it to that path that "which adb" returned.

**Comment by quarnster** [comment]
Terminal path isn't necessarily UI app path. Using the full path to adb should work if that is the case.
