### ISSUE TITLE
Syntax highlighting with threadtime enabled

### ISSUE THREAD

**Issue by Windscar** [quarnster/ADBView#26]
The nice syntax highlighting on logcat is stopped working for me.

I've tried re-installing all packages to no avail. 

using Ubuntu 12.04. 

Happy to provide any more info if needed.

**Comment by quarnster** [comment]
Define "not working". Does it say "Android Debug Bridge" in the status bar in the lower right corner? If not click the text that is there and change it to that.

**Comment by Windscar** [comment]
Well, it quite literally isn't working. I made sure to select the right Syntax Highlighting "Android Debug Bridge". 

I've tried uninstalling the package too. 

Something I noticed is that the "adb.tmLanguage" file doesn't exist under ~/.config/sublime-text-3/Packages and neither does a "ADBView" folder. 
No idea why those aren't being created. 

I've also tried manually installing the package. Even then it doesn't pick up the correct Syntax. 

I know that this used to work when I first installed it 2 weeks ago. Then one day I ran out of my Quota while installing another Sublime package. Since then I've upped my Quota, but the syntax highlighting stopped working. 

All other functionality of the plugin seems to be working just fine. 
Also, it's pretty damn awesome, so thank you for making it :)

**Comment by Windscar** [comment]
Figured it out. 

In my user settings for ADBView, I had "adb_args": ["logcat", "-v", "threadtime"]. 
When using threadtime, the syntax highlighting stops working.

**Comment by quarnster** [comment]
Supporting that would probably just be a tweak to the regexp pattern at https://github.com/quarnster/ADBView/blob/master/adb.tmLanguage#L11

**Comment by mimers** [comment]
https://github.com/quarnster/ADBView/pull/31/commits/04a06ea3f12e814f8b564f2b26276b49535c601e

this is what you want @Windscar  :)

**Comment by zjx20** [comment]
Fixed by #31
