### ISSUE TITLE
Error trying to launch ADB

### ISSUE THREAD

**Issue by rileymacdonald** [quarnster/ADBView#27]
I'm seeing this error when attempting to launch the plugin (ctrl+alt+d):
```
[u'adb', 'devices']

Traceback (most recent call last):
  File "./adbview.py", line 415, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 623, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1141, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
I used the package manager to install this plugin. My environment details are as follows:
- Licensed copy of Sublime Text 2
- OSX 10.9.5
- ADB is included in my path (/.../sdk/platform-tools/)
- Android SDK defined as $ANDROID_HOME
- Running Python 2.7.5

This plugin would be very helpful, thanks for the help!

**Comment by quarnster** [comment]
> ADB is included in my path (/.../sdk/platform-tools/)

I doubt that. Run this in ST's python console:
```python
import os; os.environ["PATH"]
```

**Comment by rileymacdonald** [comment]
I didn't realize ST didn't have access to my system path. The import command did not seem to work for me. However, I was able to install another ST package "Fix Mac Path" which immediately resolved the issue for me. Thanks!
