### ISSUE TITLE
Improvements to the package name filtering

### ISSUE THREAD

**Issue by SimonMarquis** [quarnster/ADBView#34]
The filtering by package name could be improved a bit:
- allowing multiple pid (it only uses the first pid in the list)
- listing all the matched processes by pgrep (to inform the user)
- displaying the full selected process name (instead of the value set in the settings)

**Comment by zjx20** [comment]
I don't think I will develop the feature since I did't use this plugin for a long time, but if you don't mind, please send a PR and I will take a look at it. Thanks!
